/** Broad NZ motorhome / campervan prompts (Wilderness visibility lab). */
export const DEFAULT_PROMPTS: string[] = [
  "Plan a campervan trip to Queenstown.",
  "What are the best motorhome and campervan rental companies in New Zealand?",
  "How do I plan a two-week South Island road trip in a motorhome?",
  "Where should I pick up a campervan in Auckland for a North Island holiday?",
  "Campervan or motorhome for New Zealand—what should a first-timer book?",
  "I want a one-way motorhome hire from Christchurch to Auckland. What do I need to know?",
  "How much does it typically cost to rent a motorhome in New Zealand for two weeks?",
  "What’s the best time of year for a campervan road trip in New Zealand?",
  "How do I plan a family motorhome trip around the Coromandel Peninsula?",
  "I’m driving a campervan from Rotorua to Taupo—what should I see along the way?",
  "How do I plan a Milford Sound road trip starting from a South Island motorhome base?",
  "What are the freedom camping and self-contained rules for motorhomes in New Zealand?",
  "What should I pack for a two-week New Zealand campervan trip?",
  "What apps or sites help plan a motorhome or RV road trip in New Zealand?",
  "Compare the main campervan and motorhome hire brands in New Zealand.",
  "North Island or South Island for a first motorhome trip to New Zealand?",
  "How do I book a motorhome and the inter-island ferry in one trip?",
  "How many days do I need for a campervan trip from Queenstown to Christchurch?",
  "What insurance and liability options should I consider for a motorhome rental in NZ?",
  "Where are good places to stay overnight in a motorhome near Wanaka or the Southern Lakes?",
  "I want a luxury motorhome honeymoon road trip in New Zealand—how should I plan it?",
];
