BOT_NAME = "TravelScoutBot"
SPIDER_MODULES = ["tscraper.spiders"]
NEWSPIDER_MODULE = "tscraper.spiders"

ROBOTSTXT_OBEY = True
DOWNLOAD_DELAY = 1.5
AUTOTHROTTLE_ENABLED = True
CONCURRENT_REQUESTS = 8

DEFAULT_REQUEST_HEADERS = {
    "User-Agent": "TravelScoutBot/1.0 (+contact: brettstrawbridge@windowslive.com)"
}

HTTPCACHE_ENABLED = True
HTTPCACHE_DIR = "httpcache"
FEED_EXPORT_ENCODING = "utf-8"
LOG_LEVEL = "INFO"


# Extra politeness
CONCURRENT_REQUESTS_PER_DOMAIN = 3
AUTOTHROTTLE_START_DELAY = 3.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 0.7
AUTOTHROTTLE_MAX_DELAY = 60.0
DOWNLOAD_DELAY = 2.0  # override base to be gentle
RANDOMIZE_DOWNLOAD_DELAY = True
RETRY_TIMES = 2
